# Service configuration
service:
  name: lirest-user-service
  host: HOST_NAME
  port: SERVICE_PORT
  baseUrl: SERVICE_BASE_URL

# Database configuration
postgres:
  host: POSTGRES_HOST
  port: POSTGRES_PORT
  username: POSTGRES_USERNAME
  database: POSTGRES_DATABASE
  schema: POSTGRES_SCHEMA

# API documentation configuration
api-docs:
  username: API_DOCS_USERNAME
  password: API_DOCS_PASSWORD

# Log configuration
log:
  level: LOG_LEVEL

# Kafka configuration
kafka:
  clientId: KAFKA_CLIENT_ID
  groupId: KAFKA_GROUP_ID
  serverUrl: KAFKA_SERVER_URL
  sasl:
    username: KAFKA_SASL_USERNAME
    password: KAFKA_SASL_PASSWORD
  enabled: KAFKA_ENABLED

# AWS config
aws:
  region: AWS_REGION
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
