# Service configuration
service:
  name: lirest-user-service
  host: 127.0.0.1
  port: 3001
  baseUrl: /api/v1

# Database configuration
postgres:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: '123456'
  database: lirest
  schema: user

# API documentation configuration
api-docs:
  username: ''
  password: ''

# Log configuration
log:
  level: info

# Kafka config
kafka:
  clientId: lirest-user-service
  groupId: lirest-user-service-group
  serverUrl: 'localhost:9092'
  sasl:
    username: ''
    password: ''
  enabled: false